### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by puyma** [Transcendence-pong/transcendence#70]
- [ ] Check history EVERYWHERE #73 
- [x] Tournament display order of games before first game
- [x] AI must exhibit the same speed as a regular player
- [x] When sign up new user, update avatar image not working #77 
- [ ] Check: website is protected against SQL injections/XSS.
- [ ] wss instead of ws #30 
- [x] Users can select a unique display name (and to play the tournaments) (and emails) #79
- [x] Proper default avatar #79 
- [x] friends: check #66 
- [x] store matches #66 
- [x] Nginx and avatar errors displaying + format image not accepted #91
- [ ] Nginx redirect error page #74 
- [ ] Test multiple browsers #75
